---
- name: Installation de paquets de base
  hosts: master
  become: yes
  tasks:
  - name: Installation des paquets
    apt: 
      name:
        - python
        - python3
        - vim
        - apt-transport-https
        - ca-certificates 
        - curl 
        - gnupg-agent
        - software-properties-common
      update_cache: yes

  - name: Alias python
    lineinfile:
      path: /root/.bashrc
      regexp: '^alias python='
      line: alias python=python3
      state: present
      insertafter: EOF
      create: True
      owner: root

  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable

  - name: install docker 
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - python3-docker
      update_cache: yes

  - name: add userpermissions
    shell: "usermod -aG docker {{ lookup('env','USER') }}"

  # Installs Docker SDK
  # --
  # 
  - name: install python package manager
    apt:
      name: python3-pip
  
  - name: install python sdk
    pip:
      name:
        - docker
        - docker-compose
